---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    challenge.app: telegram-notify-bot
  name: telegram-notify-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      challenge.app: telegram-notify-bot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        challenge.app: telegram-notify-bot
        team: DevOps
    spec:
      containers:
        - name: telegram-notify-bot
          envFrom:
            - configMapRef:
                name: telegram-notify-bot-config
          image: gitea.dxas90.xyz/dxas90/telegram-notify-bot:latest
          resources:
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      # https://kubernetes.io/docs/concepts/containers/images/#referring-to-an-imagepullsecrets-on-a-pod
      imagePullSecrets:
        - name: pull-registry
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegram-notify-bot-config # line 49
data:
  APP_ENV: prod
  APP_THREADS: "1"
  INTERVAL: "30"
  LOGLEVEL: info
  REDIS_DSN: "redis://redis.infrastructure.svc:6379?timeout=0.5"
  TOKEN: "CHANGE_ME"
